### ISSUE TITLE
Re-design the background fetcher 

### ISSUE THREAD

**Issue by rdpsin** [awslabs/soci-snapshotter#106]
**Is your feature request related to a problem? Please describe.**
The background fetcher is the component of the snapshotter that fetches spans in the background. In it's current state, it is not a particularly well-thought-out component, leaking abstractions and degrading snapshotter performance.

Some of the issues:

- The background fetcher acquires the lock and only releases it when it's done fetching the span from remote. This can lead to situations like #105, wherein on-demand fetches suffer due to lock contention.

- The background fetcher is very aggressive; currently, it tries to fetch all spans from all layers as fast as possible. This is undesirable (e.g., there might be cases we want to rate limit the background fetcher to avoid throttling, or prioritize certain layers' prefetch over others). 

- The background fetcher fetches a single span at a time. This is fine for when a span size is a desirable value (for e.g., 8-10MiB for S3), but no so much when it's not. For some span sizes and some repos, it may be more performant to fetch multiple spans at once.

**Describe the solution you'd like**
The background fetcher is re-architected and takes into consideration all the above points.

**Comment by jamesmt-aws** [comment]
When we are fetching spans from S3-backed container registries like ECR and Dockerhub, we should be following the best practices for S3. Those include:
- Scale Connections Horizontally, so that multiple fetches are performed in parallel
- Use byte range fetches in the 8-16MiB range. If we set the span size to 8MiB we'd do this naturally, and 4MiB probably isn't too far off, but in the 4MiB span world fetching two spans at a time seems like a good idea. 
- Retry requests that are taking too long. 

All of this stuff is implemented in the AWS S3 SDK. I'm not sure if it's appropriate for SOCI to depend on that library, or if it makes more sense for us to reimplement that stuff ourselves, but I think it's important to follow best practices here. 

Here's the page on [Performance Guidelines for Amazon S3](https://docs.aws.amazon.com/AmazonS3/latest/userguide/optimizing-performance-guidelines.html) for reference.

**Comment by rdpsin** [comment]
Implemented in PR #214.
