### ISSUE TITLE
[BUG] Re-use `http.Client` across all layers/retrieving SOCI artifacts

### ISSUE THREAD

**Issue by kzys** [awslabs/soci-snapshotter#224]
**Describe the bug**

Currently SOCI snapshotter doesn't cache HTTP responses' Authorization header in the process-wide level. So the snapshotter is getting HTTP 401 Unauthorized multiple times.

This is bad because
- It would negatively impact the duration to get the initial bytes from a container image by sending extra requests.
- It would generate extra load to container image registries.

**Steps To Reproduce**

Use SOCI snapshotter with a private image where Authorization header is required.

**Expected behavior**

SOCI snapshotter receives 401 first, but the result will be cached and it won't get 401 anymore for subsequent requests.

**Configuration (please complete the following information):**
 - OS: Amazon Linux 2
 - Snapshotter Version: Will check
 - Containerd Version: Will check

**Additional context**

**Comment by hanyuel** [comment]
[docker.Authorizer](https://github.com/awslabs/soci-snapshotter/blob/main/service/resolver/registry.go#L94-L96) is created when [HTTP fetcher](https://github.com/awslabs/soci-snapshotter/blob/main/fs/remote/resolver.go#L203-L204) is created for each layer during the layer being mounted/resolved. Therefore, each layer has its own ``docker.Authorizer``, so the 401 Unauthorized result is not shared between layers. Hence we are seeing multiple 401s each of which is for one layer resolving. 

To resolve the issue, we should have just one ``docker.Authorizer`` (in ``fs``) shared by all layers. 

However, the change would be a refactoring that is much larger than just moving``docker.Authorizer``  from the layer level to the fs level. Note that ``docker.Authorizer`` is created with [http.client](https://github.com/awslabs/soci-snapshotter/blob/main/service/resolver/registry.go#L95) and [reference.Spec](https://github.com/awslabs/soci-snapshotter/blob/main/service/resolver/registry.go#L96) both of which are created per layer. To share ``docker.Authorizer`` among layers, we need to have ``http.client`` shared by all layers as well. Also, ``ref.Spec`` is retrieved from [source information of a layer](https://github.com/awslabs/soci-snapshotter/blob/main/fs/fs.go#L391) which seems to be layer-specific information, so that needs to be refactored in order to make ``docker.Authorizer`` shareable by all layers.

**Comment by sparr** [comment]
Idea: Stick with one `docker.Authorizer` per layer. Cache [responses](https://github.com/awslabs/soci-snapshotter/blob/2fbb32115aadea5063c5ee9fa20e41aee271001b/fs/remote/resolver.go#L302) at the fs level and use them to prime later `Authorizer` instances via `.AddResponses()`.

**Comment by sparr** [comment]
@kzys Can you clarify that you want this behavior to apply at the file level? In theory a server could produce 401 for a request for a file with some request headers (e.g. a particular range) but a 200 for the same file with different headers, but I think we'd be comfortable ignoring that possibility here.

**Comment by kzys** [comment]
What are the benefits of ignoring the possibility? Simplicity of our implementation?

**Comment by sparr** [comment]
I am unclear on the use case for caching specific range requests (or a request without a range). My understanding is that any such request would only be made once, so the cache wouldn't be useful with that granularity.

**Comment by turan18** [comment]
Blocked on design #759
