### ISSUE TITLE
[FEATURE] Add FUSE operation failure metrics

### ISSUE THREAD

**Issue by Kern--** [awslabs/soci-snapshotter#274]
**Is your feature request related to a problem? Please describe.**
Currently, we use a state file in the FUSE filesystem to report errors that occur in that filesystem. This is good for logging errors, but doesn't provide metrics.

**Describe the solution you'd like**
A prometheus metric for number of failures for each FUSE operation.

**Describe alternatives you've considered**
We could alternatively parse the state file and create metrics from that data, however this seems like an extra step seeing as the snapshotter already emits metrics itself.

**Additional context**

**Comment by djdongjin** [comment]
@Kern-- 

Do we want to log all fuse op failures in metrics (e.g. whenever the return errno is not zero), or we want to keep the failure metircs consistent with when we record a fuse op failure  in the state file?

As an example, [node.Getattr](https://github.com/awslabs/soci-snapshotter/blob/0f66ca64e0099f7573bb6c3b0009d0c51468261a/fs/layer/node.go#L357) doesn't record failure; [node.Lookup](https://github.com/awslabs/soci-snapshotter/blob/0f66ca64e0099f7573bb6c3b0009d0c51468261a/fs/layer/node.go#L258) only record specific failures.

I prefer the 2nd option, otherwise we might have a higher fuse op failure metric, but we cannot find corresponding record in state file to debug. It also makes it easy to fine-tune how we categorize fuse op failures.

**Comment by Kern--** [comment]
> fuse op failures in metrics (e.g. whenever the return errno is not zero)

Non-zero errno does not necessarily mean a fuse op failed. For example, `ENOENT` is returned if a file doesn't exist which is not a failure. 

We should report and increment our metric whenever we return `EIO`.

**Comment by djdongjin** [comment]
> We should report and increment our metric whenever we return `EIO`.

The PR is updated to keep metrics and report consistent (only inc metric when reporting failure in state file).
