### ISSUE TITLE
[Bug] `soci-snapshotter-grpc` cannot start if there is snapshots with expired credentials

### ISSUE THREAD

**Issue by djdongjin** [awslabs/soci-snapshotter#487]
### Description

1. If you have snapshots in soci's `/var/lib/soci-snapshotter-grpc/snapshotter/snapshots`, `soci-snapshotter-grpc` cannot start if some of the snapshots require credential but expired.
2. `/var/lib/soci-snapshotter-grpc/snapshotter/snapshots` has snapshots, but they didn't show up in `ctr snapshot ls`.
3. How do we handle the scenario where a user `rpull` an image with temp credential (like ECR) and after a while, start a container (temp credential expired).

### Steps to reproduce the bug

For 1: (401 Unauthorized error)

```shell
$ sudo ls /var/lib/soci-snapshotter-grpc/snapshotter/snapshots
57  58  59  60  61  62  63  64  65  66
$ sudo soci-snapshotter-grpc
...
{"level":"info","msg":"preparing filesystem mount at mountpoint=/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/60/fs","time":"2023-03-10T13:22:13.854793834Z"}
{"digest":"sha256:c49213575c1edfb320b1e35def5d4b8aea1bc78a474095f2e94c7b8ce9313d1e","level":"info","mountpoint":"/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/60/fs","msg":"fetching SOCI artifacts using index descriptor","time":"2023-03-10T13:22:13.854858908Z"}
{"digest":"sha256:c49213575c1edfb320b1e35def5d4b8aea1bc78a474095f2e94c7b8ce9313d1e","level":"info","mountpoint":"/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/60/fs","msg":"fetching SOCI index from remote registry","time":"2023-03-10T13:22:13.854904684Z"}
{"level":"info","mountpoint":"/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/60/fs","msg":"Received status code: 401 Unauthorized. Refreshing creds...","src":"xxx.dkr.ecr.us-east-1.amazonaws.com/rabbitmq:latest/sha256:9f1239da988218e95bdf8e2e5ed09f621cf30c87824a1a18b09579ea804aa875","time":"2023-03-10T13:22:13.876989933Z"}
{"level":"info","mountpoint":"/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/60/fs","msg":"Received status code: 401 Unauthorized. Refreshing creds...","src":"xxx.dkr.ecr.us-east-1.amazonaws.com/rabbitmq:latest/sha256:9e3ecea6951a3ff9d1a48b5a5bd92c2f2dfff76055eb42d29409eae590ded003","time":"2023-03-10T13:22:13.877309592Z"}
{"error":"failed to restore remote snapshot: failed to prepare remote snapshot: sha256:925f73080f6fadbfb56ba617598aa9a420a353db77db214cb3701c831db8694a: failed to resolve layer \"sha256:9e3ecea6951a3ff9d1a48b5a5bd92c2f2dfff76055eb42d29409eae590ded003\" from \"xxx.dkr.ecr.us-east-1.amazonaws.com/rabbitmq:latest\": failed to resolve the blob: failed to resolve the source: cannot resolve layer: failed to redirect (host \"xxx.dkr.ecr.us-east-1.amazonaws.com\", ref:\"xxx.dkr.ecr.us-east-1.amazonaws.com/rabbitmq:latest\", digest:\"sha256:9e3ecea6951a3ff9d1a48b5a5bd92c2f2dfff76055eb42d29409eae590ded003\"): failed to access to the registry with code 403: failed to resolve","level":"fatal","msg":"failed to create new snapshotter","time":"2023-03-10T13:22:13.886973693Z"}
```

For 2:

```shell
$ sudo ls /var/lib/soci-snapshotter-grpc/snapshotter/snapshots
57  58  59  60  61  62  63  64  65  66
$ sudo ctr snapshot ls
KEY PARENT KIND
```

### Describe the results you expected

Having a bad snapshot shouldn't stop soci snapshotter from start, it should log a warning and continue to start.

soci snapshots should show up in `sudo ctr snapshot`.

### Host information

1. OS: AL2
2. Snapshotter Version: main
3. Containerd Version: 1.7 beta

**Comment by turan18** [comment]
We should verify if this is fixed with the [AllowInvalidMountsOnRestart](https://github.com/awslabs/soci-snapshotter/blob/5a40aff504535a863e0655de76a77b058184cafc/config/service.go#L79) config set.

**Comment by sondavidb** [comment]
I was able to recreate this bug after a bit of fiddling. A more granular recreation is outlined as follows:

1. Pull an image from a repo that needs credentials (validating via `docker login` or anything else that uses docker credentials)
2. Create a SOCI index from the image and push it to aforementioned repo
3. Start `soci-snapshotter-grpc` and pull the image with SOCI (`soci rpull --user [username]:[password] --soci-index-digest [sha256 hash of digest] [image URI]`).
4. Kill the daemon (`sudo killall soci-snapshotter-grpc`).
5. Unmount the newly mounted fuse filesystems
6. Remove stored docker credentials (by default located in `~/.docker/config.json` and /root/.docker/.config.json')
7. Start snapshotter (`sudo soci-snapshotter-grpc`).

The daemon will throw the error mentioned in the first post before quitting.

The config set mentioned by @turan18 does fix this issue (setting `allow_invalid_mounts_on_restart=true` in `/etc/soci-snapshotter-grpc/config.toml`), allowing the daemon to start with a bad snapshot loaded, but also allows the snapshotter to start with other errors.

For example, when following the above steps but using nerdctl (as in the [Getting Started guide](https://github.com/awslabs/soci-snapshotter/blob/ec1e62326578318ace5048c487b7e155a068dd4b/docs/getting-started.md?plain=1#L237)) instead of `soci rpull`, the error thrown states that it cannot find the digest, as it is not specified, yet the daemon continues to start. Admittedly, it is pretty closely related to this error mentioned above, as it is also an issue with a specific snapshot as opposed to the service as a whole.

Perhaps this is still the best mitigation/"fix" we can deliver, but I believe we should keep this in mind. For now, we can simply let users ignore the error, and perhaps close this issue.

**Comment by turan18** [comment]
Nice, thanks for confirming! I think the case of a missing index digest is similar to the one described in the original issue except that it happens earlier the call stack when we try to get the index digest when creating a SOCI context. In that case, we'd still need credentials since we'll need to make a referrers API call. I think we can close this issue as it's the orchestrator/users job to handle credentials.
