### ISSUE TITLE
[Dependency] Updating to containerd 1.7.0

### ISSUE THREAD

**Issue by turan18** [awslabs/soci-snapshotter#498]
### Description

Containerd 1.7.0 was released recently. The goal of this issue is to investigate and determine any hurdles/changes that are needed either within the snapshotter or the cli to upgrade to containerd 1.7.0. If there are no immediate/large changes required we can go forth with the upgrade. However, if there changes needed we should note them within this issue and  either create separate issues for each change or one large issue tracking each depending on how many changes would be needed/how large the changes are.

### Describe the results you expected

Identify changes, if any are needed, to upgrade to containerd 1.7.0 and if there are changes needed create issues for them.

### Host information

1. OS: 
2. Snapshotter Version: 
3. Containerd Version:

**Comment by djdongjin** [comment]
While updating to containerd 1.7.0, we can replace our "old" cri-api dependency (`k8s.io/cri-api v0.25.7`) to containerd's third-party fork (`github.com/containerd/containerd/third_party/k8s.io/cri-api`).

I believe this is how containerd (and stargz) supports both cri v1alpha2 and cri v1 API (i.e. use `k8s.io/cri-api` for latest v1 API and maintain a fork of `cri-api` in its repo for v1alpha2 api. And since containerd already has such a fork in its repo, we probably can just use that.

When later we plan to support cri v1 API, we can add `k8s.io/cri-api` back which includes the v1 API.

An example of how containerd use both APIs:

https://github.com/containerd/containerd/blob/1fbd70374134b891f97ce19c70b6e50c7b9f4e0d/pkg/cri/server/version.go#L22-L24

**Comment by sparr** [comment]
Do we intend to maintain 1.6.x compatibility for some duration? A change of this sort may eventually necessitate running tests with multiple dependency versions.

**Comment by djdongjin** [comment]
> Do we intend to maintain 1.6.x compatibility for some duration? 

I believe we need to keep 1.6.x for a long duration... I feel the upgrade/adoption process will be quite slow.

> A change of this sort may eventually necessitate running tests with multiple dependency versions.

Yeah we should add different containerd version in our CI. GH action matrix should be able to do that.

Meanwhile, I think we need to re-evaluate our containerd support policy. Right now we claim we support containerd >= 1.4, but we only test on 1.6.x.

**Comment by Kern--** [comment]
As far as compatibility goes, I think we should aim for supporting all supported versions of containerd. When we have kubernetes support, we should also support all supported versions of kubernetes.

**Comment by Kern--** [comment]
We should add a containerd matrix to integ tests before doing this. Blocked on #500
