### ISSUE TITLE
Add `soci index rm` command

### ISSUE THREAD

**Issue by rdpsin** [awslabs/soci-snapshotter#70]
**Is your feature request related to a problem? Please describe.**
We currently don't have any way to remove ind(exes/ices) from the local store. We should add commands to do so in the SOCI CLI.

**Describe the solution you'd like**
`soci index rm <digest>` - allows you to remove a particular index by specifying the index digest (as presented by `soci index list`) and its entry in the artifact database.

`soci index rm --all` - removes all ind(exes/ices) from the local store and their entries in the artifact database.

**Describe alternatives you've considered**
I'm a little torn on `soci index rm --all`. Maybe it should be a separate command i.e, something like`soci index prune`?

**Additional context**

**Comment by wmesard** [comment]
Request for clarification: Would this command also delete the zTOCs blobs contained in the index? What if the zTOCs are part of multiple SOCI indices (e.g., if it's from a base index layer used by multiple container images)? To do this right, we'd either have to sign up for reference counting, or periodic garbage collection sweeps.

Maybe that's the right thing to do. But maybe we should wait until we can use the containerd store to store the SOCI artifacts, rather than reinvent that wheel.

**Comment by wmesard** [comment]
Agree about `rm --all`. Users should probably have to work a little harder to shoot themselves in the foot. I would be in favor of adding a `-q` option to `soci index list` though (following the precedent set by nerdctl). Then users could say
```
soci index rm $(soci index list -q )
```
And `soci index rm --ref <image-digest>` would be nice.

**Comment by rdpsin** [comment]
My initial thought was that only index blobs would be deleted + entry deleted from the db. That ztoc deletion should be part of `soci ztoc rm` command. That does raise the question of what happens to indexes if ztocs are deleted. I don't have the answer to that.

**Comment by torredil** [comment]
3

**Comment by wmesard** [comment]
This was pointed at "3" after the following discussion:

This issue is just to delete the SOCI index manifest, but not delete the zTOCs. TBD whether zTOCs need to be cleaned up by hand (which would require a `soci ztoc rm`, as described above), or whether we would get all fancy and implement garbage collection of orphaned zTOCs.

A one-pager is probably needed to describe what we want the holistic artifact management experience to be, and then see what stories fall out of that.

But the immediate pain point is that if you create a second SOCI index for an image, but want `soci push` to upload the first one, you can't today.
