### ISSUE TITLE
Remove dependency on `ghcr.io/oci-playground/registry:v3.0.0-alpha.1` since its only available for `amd64` architectures. Since the notion of OCI Artifact Manifests have seemingly been rejected from the v1.1.0 Image Spec I don't think we need a v1.1.0 compliant registry at least until the v1.1.0 spec has been finalized. We can then remove any tests that use this image - https://github.com/awslabs/soci-snapshotter/blob/main/integration/push_test.go#L133 and then set the default registry to be `registry:2` here https://github.com/awslabs/soci-snapshotter/blob/main/integration/util_test.go#L423

### ISSUE THREAD

**Issue by turan18** [awslabs/soci-snapshotter#714]

**Comment by sparr** [comment]
Remainder of previous title:

Remove dependency on `ghcr.io/oci-playground/registry:v3.0.0-alpha.1` since its only available for `amd64` architectures. Since the notion of OCI Artifact Manifests have seemingly been rejected from the v1.1.0 Image Spec I don't think we need a v1.1.0 compliant registry at least until the v1.1.0 spec has been finalized. We can then remove any tests that use this image - https://github.com/awslabs/soci-snapshotter/blob/main/integration/push_test.go#L133 and then set the default registry to be `registry:2` here https://github.com/awslabs/soci-snapshotter/blob/main/integration/util_test.go#L423
