### ISSUE TITLE
[FEATURE] Support SOCI Indexes without any zTOCs

### ISSUE THREAD

**Issue by ollypom** [awslabs/soci-snapshotter#717]
### Description

When working with very small container images, such as side car containers (like logging and monitoring), I would like the ability to create a SOCI Index without any zTOCs. 

The use case I have in mind is where a potential sidecar container is very small (<10MB) and will not benefit from being lazy loaded, but needs to have a SOCI Index to prevent the whole Task / Pod from failing back to overlayfs.

Current `soci` cli behaviour:

```bash
$ sudo soci --debug create 111222333444.dkr.ecr.us-east-1.amazonaws.com/myworkload:v0.1
ztoc skipped - layer sha256:c1d6d1b2d5a367259e6e51a7f4d1ccd66a28cc9940d6599d8a8ea9544dd4b4a8 (application/vnd.oci.image.layer.v1.tar+gzip) size 2807669 is less than min-layer-size 10485760
ztoc skipped - layer sha256:4e008c112df3add4433c8a310126d95e8e03ead5e51daa29c4843711de841aa8 (application/vnd.oci.image.layer.v1.tar+gzip) size 4879127 is less than min-layer-size 10485760
soci: no ztocs created, all layers either skipped or produced errors

$ sudo soci index ls
DIGEST    SIZE    IMAGE REF    PLATFORM    MEDIA TYPE    CREATED
```

**Comment by turan18** [comment]
Hey, thanks for opening the issue! Many registries perform a validation on the image manifest(s) being pushed. One of these is making sure that an image manifest has at least one layer. Since this constraint is not universally adopted by all registries, we opted to throw an error when creating empty indexes to create a somewhat uniform experience.

**Comment by Kern--** [comment]
If there's no objections, I'm going to close this.
