### ISSUE TITLE
[FEATURE] beautify `soci index info` command output

### ISSUE THREAD

**Issue by austinvazquez** [awslabs/soci-snapshotter#865]
### Description

The JSON output from `soci index info <hash>` is a unformated JSON blob.

### Describe the solution you'd like

It would be nice to have this JSON passed through a formatter before output to console.

### Describe any alternative solutions/features you've considered

Alternatively, users can do something like the following without any changes to the SOCI CLI:

```
soci index info <hash> | python -m json.tool
```

**Comment by Kern--** [comment]
IIRC, this implementation was to avoid unmarshal into the `soci.Index` type because at the time we had 2 serialized forms and so you couldn't just `json.MarshalIndent` on the in-memory representation and get back the right structure.

https://github.com/awslabs/soci-snapshotter/blob/6fb58b582f4d01c9399387ef606ee23e36fc9e5b/cmd/soci/commands/index/info.go#L66C35-L66C35

We could unmarshal into a `map[string]interface{}` instead of `soci.Index` and then immediately `json.MarshalIndent` on that.
