### ISSUE TITLE
Allow manually remove invalid snapshots on restore

### ISSUE THREAD

**Issue by vkuzniet** [awslabs/soci-snapshotter#93]
**Is your feature request related to a problem? Please describe.**
On restart, soci-snapshotter-grpc doesn't start if one of the snapshots cannot restore. This makes impossible to manually remove images and snapshots (e.g. by using ctr).

**Describe the solution you'd like**
Cherrypick https://github.com/containerd/stargz-snapshotter/pull/901

**Describe alternatives you've considered**

**Additional context**

**Comment by hanyuel** [comment]
This problem that this issue tries to fix is that if the snapshotter crashes, it won't be able to restart because the snapshotter won't be able to restore the remote snapshots ([this](https://github.com/awslabs/soci-snapshotter/blob/main/snapshot/snapshot.go#L177) will error out), so it will crash again and again.

I was not able to reproduce the problem by killing (SIGKILL-ing) the soci-snapshotter-grpc process when the container is running. I might have repro'd once... Here are the steps I did:
1. start soci-snapshott-grpc
2. soci image rpull $IMAGE
3. soci run $IMAGE
4. sudo kill -9 process-id-of-soci-snapshotter-grpc
5. ctr i rm $IMAGE
6. repeat step 1,2,3
